# 
#  GitHub Action Part-1 Basic
#
#  Copyleft (c) by Vovik 2022
#

name: My-GitHubActins-Basics
env:
  APPLICATION_NAME    : "MyFlask" 
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
     branches: [ master ]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "my_testing"
  my_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Hello Message in testing
        run : echo "Hello World from Testing job"
        
      - name: Execure few commands
        run : |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
        
      - name: List current folder
        run : ls -la 
        
      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: List current folder
        run : ls -la
        
  my_deploy:  
    runs-on: ubuntu-latest
    needs: [my_testing] # it will work after my_testing
    
    steps:
      - name: Print Hello Message in deploy
        run : echo "Hello World from Deploy job"
        
      - name: Printing Deployment package
        run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
      - name: Let's test some packages if they are here 1
        run : aws --version

      - name: Let's test some packages if they are here 2
        run : zip
